### ISSUE TITLE
Unable to get this to display images

### ISSUE THREAD

**Issue by christraverse** [EP-NY/shopify-scss-asset-helper#1]
Using a combo of:

@mixin background-file($asset-image-with-extension) {
  background-image: url(' {{ "#{$asset-image-with-extension}" | asset_url }} ')
}

and 

@include background-file('image.png');

results in the following css being output to my page.

background-image: url(' {{ "image.png" | asset_url }} ');

This does not display the actual image.  Any suggestions?

**Comment by josephbergdoll** [comment]
that is expected behavior – make sure you are compiling to a `*.scss.liquid` file.
