### ISSUE TITLE
Liquid syntax error (regexp)

### ISSUE THREAD

**Issue by FreekGielen** [EP-NY/shopify-scss-asset-helper#2]
When I try to add the mixin to my **theme.scss.liquid** file I get an error:

```
@mixin background-file($asset-image-with-extension) {
    background-image: url(' {{ "#{$asset-image-with-extension}" | asset_url }} ')
}
```

**Liquid syntax error: Variable '{{ "#{$asset-image-with-extension}' was not properly terminated with regexp: /}}/**

How did you managed to get it work?

**Comment by josephbergdoll** [comment]
@fumpr this is not supposed to be added to your theme.scss.liquid file. It is meant for SCSS files that are preprocessed locally (via grunt, gulp, CodeKit, etc) into the final .scss.liquid file you will then upload, as is referenced in the article -> https://medium.com/@josephbergdoll/writing-sass-for-shopify-22c7568dd8f2

**Comment by fumpr** [comment]
@josephbergdoll Yes I understand, I have a css/theme.scss.liquid file where I import al the files, one of them being **@import url('helpers/mixins.scss.liquid');** , this mixing contains the code above.


My gulpfile contains 
```
// https://github.com/unlight/gulp-cssimport
var gulp = require('gulp');
var cssimport = require("gulp-cssimport");

// Process CSS
gulp.task('styles', function(){
    return gulp.src('css/**/*.*')
        .pipe(cssimport())
        .pipe(gulp.dest('assets/'));
})

// Watch files
gulp.task('watch', function () {
    gulp.watch('css/**/*.*', ['styles']);
});

// Default task
gulp.task('default', ['watch']);
```

Am I missing something?
Thanks for your time
